

USE CAMP_BRAS_LUCAS

SELECT A.UF, SUM(B.VITORIAS*3+B.EMPATES) AS PONTOS FROM TBEQUIPE A INNER JOIN TBRESULTADO B ON(A.SIGLA = B.SIGLA)
WHERE A.UF IN('SP','RJ','ES','MG') GROUP BY A.UF 
HAVING SUM(B.VITORIAS*3+B.EMPATES) >= 20

SELECT SIGLA, VITORIAS, EMPATES, DERROTAS, ((VITORIAS*3)+EMPATES) AS PONTOS FROM TBRESULTADO 
ORDER BY PONTOS 

SELECT NOME_EQUIPE FROM TBEQUIPE WHERE NOT EXISTS (SELECT * FROM TBRESULTADO WHERE TBEQUIPE.SIGLA = TBRESULTADO.SIGLA)

SELECT NOME_EQUIPE, NOMEUF FROM TBUF LEFT OUTER JOIN TBEQUIPE 
ON(TBUF.UF = TBEQUIPE.UF)

SELECT NOME_EQUIPE, NOMEUF FROM TBUF RIGHT OUTER JOIN TBEQUIPE 
	ON(TBUF.UF = TBEQUIPE.UF)

	FULL OUTER JOIN 


SELECT NOME_EQUIPE, NOMEUF FROM TBUF FULL OUTER JOIN TBEQUIPE 
ON(TBUF.UF = TBEQUIPE.UF)

SELECT COUNT(UF) AS NUMESTADOS FROM TBUF 

SELECT COUNT(SIGLA) AS EQUIPES FROM TBRESULTADO

SELECT COUNT(SIGLA) AS EQUIPES FROM TBEQUIPE

SELECT UF, COUNT(NOME_EQUIPE) AS NUMEQUIPES FROM TBEQUIPE
GROUP BY UF ORDER BY UF 


SELECT TBEQUIPE.UF, SUM(TBRESULTADO.VITORIAS) AS VITORIAS FROM TBEQUIPE 
INNER JOIN TBRESULTADO ON(TBEQUIPE.SIGLA = TBRESULTADO.SIGLA)
GROUP BY TBEQUIPE.UF HAVING SUM(TBRESULTADO.VITORIAS) > 30